wandb_version: 1

tag:
  desc: null
  value: fsc-baseline
device:
  desc: null
  value: '0'
no_wandb:
  desc: null
  value: false
data_dir:
  desc: null
  value: ./datasets/FSC
log_param:
  desc: null
  value: 100.0
crop_size:
  desc: null
  value: 384
downsample_ratio:
  desc: null
  value: 16
dcsize:
  desc: null
  value: 8
lr:
  desc: null
  value: 4.0e-05
batch_size:
  desc: null
  value: 8
num_workers:
  desc: null
  value: 4
weight_decay:
  desc: null
  value: 1.0e-05
max_epoch:
  desc: null
  value: 1000
val_epoch:
  desc: null
  value: 10
val_start:
  desc: null
  value: 100
scheduler:
  desc: null
  value: step
step:
  desc: null
  value: 400
gamma:
  desc: null
  value: 0.5
t_max:
  desc: null
  value: 200
eta_min:
  desc: null
  value: 4.0e-06
save_dir:
  desc: null
  value: ./checkpoint
save_all:
  desc: null
  value: false
max_model_num:
  desc: null
  value: 1
resume:
  desc: null
  value: ''
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684493169.561657
    t:
      1:
      - 1
      - 41
      - 51
      - 55
      2:
      - 1
      - 41
      - 51
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.8.10
      5: 0.15.3
      8:
      - 5
